name: Port GKI 5.4 to Non-GKI (From External Repos)

on: workflow_dispatch: inputs: gki_repo: description: 'URL of GKI Kernel 5.4 repo' required: true default: 'https://github.com/official-devs/gki-kernel-5.4' dtb_repo: description: 'URL of DTB Source Tree 4.9 repo' required: true default: 'https://github.com/official-devs/kernel-dtb-4.9' gki_branch: description: 'Branch of GKI kernel' required: false default: 'main' dtb_branch: description: 'Branch of DTB source' required: false default: 'main' device_defconfig: description: 'Name of the device defconfig file (e.g. beryllium_defconfig)' required: true

jobs: port_kernel: runs-on: ubuntu-latest

steps:
  - name: Clone GKI Kernel Source
    run: |
      git clone --depth=1 --branch "${{ github.event.inputs.gki_branch }}" "${{ github.event.inputs.gki_repo }}" gki-kernel

  - name: Clone DTB Source Tree 4.9
    run: |
      git clone --depth=1 --branch "${{ github.event.inputs.dtb_branch }}" "${{ github.event.inputs.dtb_repo }}" dtb-source-4.9

  - name: Install Dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y dtc bc build-essential libncurses5-dev bison flex libssl-dev libelf-dev curl git gcc make clang lld

  - name: Inject DTB Files
    run: |
      cp -r dtb-source-4.9/* gki-kernel/arch/arm64/boot/dts/qcom/

  - name: Setup Toolchain
    run: |
      mkdir -p toolchains
      curl -L https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/master-kernel/clang-r416183b.tar.gz?format=TEXT | base64 -d | tar -xz -C toolchains

  - name: Build Kernel
    run: |
      cd gki-kernel
      export ARCH=arm64
      export SUBARCH=arm64
      export CROSS_COMPILE=aarch64-linux-gnu-
      export CLANG_TRIPLE=aarch64-linux-gnu-
      export PATH=$GITHUB_WORKSPACE/toolchains/clang-r416183b/bin:$PATH

      make O=out ${{ github.event.inputs.device_defconfig }} CC=clang
      make O=out -j$(nproc) CC=clang Image.gz-dtb

  - name: Upload Final Image.gz-dtb
    uses: actions/upload-artifact@v3
    with:
      name: compiled-image-gz-dtb
      path: gki-kernel/out/arch/arm64/boot/Image.gz-dtb

