# GitHub Actions Workflow: Port GKI 5.4 to Non-GKI Kernel (DTB & defconfig dari kernel 4.9)
# ==========================================================================================
# Fungsi:
# - Clone kernel GKI 5.4 dari repositori GitHub
# - Clone DTB dan device_defconfig dari kernel 4.9 source tree lain
# - Build kernel non-GKI dengan DTB dan defconfig dari kernel 4.9
# - Upload hasil: Image.gz-dtb

name: Port-GKI-5.4-to-Non-GKI

on:
  workflow_dispatch:
    inputs:
      gki_repo:
        description: 'URL repositori GKI Kernel 5.4'
        required: true
        default: 'https://github.com/pundiramit/linux'
      gki_branch:
        description: 'beryllium-mainline'
        required: false
        default: 'beryllium-mainline'
      non_gki_repo:
        description: 'URL repositori kernel 4.9 (sumber DTB dan defconfig)'
        required: true
        default: 'https://github.com/RONNIE158/android_kernel_xiaomi_sdm845'
      non_gki_branch:
        description: 'lineage-21'
        required: false
        default: 'lineage-21'
      defconfig_path:
        description: 'Path relatif ke file defconfig di repo kernel 4.9 (contoh: arch/arm64/configs/beryllium_defconfig)'
        required: true

jobs:
  build:
    name: Port & Build Non-GKI Kernel
    runs-on: ubuntu-latest

    steps:
      - name: Clone GKI Kernel Source
        run: |
          git clone --depth=1 --branch "${{ github.event.inputs.gki_branch }}" "${{ github.event.inputs.gki_repo }}" gki-kernel

      - name: Clone Kernel 4.9 Source (defconfig & DTB)
        run: |
          git clone --depth=1 --branch "${{ github.event.inputs.non_gki_branch }}" "${{ github.event.inputs.non_gki_repo }}" kernel-4.9

      - name: Install Dependencies (tanpa dtc)
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential libncurses5-dev bison flex libssl-dev libelf-dev curl git gcc make lld

      - name: Download prebuilt DTC binary
        run: |
          mkdir -p dtc-bin && cd dtc-bin
          curl -LO https://github.com/cran/dtc-prebuilt/releases/download/v1.6.0/dtc-linux-x86_64
          chmod +x dtc-linux-x86_64
          sudo mv dtc-linux-x86_64 /usr/local/bin/dtc

      - name: Download Prebuilt Toolchains (Clang + GCC)
        run: |
          mkdir -p toolchains && cd toolchains

          git clone --depth=1 -b lineage-20.0 https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b clang
          git clone --depth=1 -b lineage-19.1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 aarch64
          git clone --depth=1 -b lineage-19.1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 arm

      - name: Copy DTB & defconfig dari kernel 4.9 ke GKI
        run: |
          mkdir -p gki-kernel/arch/arm64/boot/dts/qcom
          cp -r kernel-4.9/arch/arm64/boot/dts/qcom/* gki-kernel/arch/arm64/boot/dts/qcom/
          cp kernel-4.9/${{ github.event.inputs.defconfig_path }} gki-kernel/arch/arm64/configs/

      - name: Build Kernel Image.gz-dtb
        run: |
          cd gki-kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=$GITHUB_WORKSPACE/toolchains/aarch64/bin/aarch64-linux-android-
          export CROSS_COMPILE_ARM32=$GITHUB_WORKSPACE/toolchains/arm/bin/arm-linux-androideabi-
          export PATH=$GITHUB_WORKSPACE/toolchains/clang/bin:$PATH

          defconfig_file=$(basename "${{ github.event.inputs.defconfig_path }}")
          make O=out $defconfig_file CC=clang
          make O=out -j$(nproc) CC=clang Image.gz-dtb

      - name: Upload Image.gz-dtb
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image-gz-dtb
          path: gki-kernel/out/arch/arm64/boot/Image.gz-dtb
