# GitHub Actions Workflow: Port GKI 5.4 to Non-GKI Kernel (DTB 4.9)
# ================================================================
# Fungsi:
# - Clone kernel GKI 5.4 dari repositori GitHub
# - Clone DTB dari kernel 4.9 dari repositori GitHub
# - Gabungkan dan modifikasi menjadi kernel non-GKI
# - Build kernel pakai toolchain Clang
# - Upload hasil: Image.gz-dtb

name: Port-GKI-5.4-to-Non-GKI

on:
  workflow_dispatch:
    inputs:
      gki_repo:
        description: 'URL repositori GKI Kernel 5.4'
        required: true
        default: 'https://github.com/pundiramit/linux'
      dtb_repo:
        description: 'URL repositori DTB Kernel 4.9'
        required: true
        default: 'https://github.com/RONNIE158/android_kernel_xiaomi_sdm845'
      gki_branch:
        description: 'Branch kernel GKI'
        required: false
        default: 'lineage-21'
      dtb_branch:
        description: 'Branch kernel DTB 4.9'
        required: false
        default: 'beryllium-mainline'
      device_defconfig:
        description: 'File defconfig device (contoh: beryllium_defconfig)'
        required: true

jobs:
  build:
    name: Build Kernel Non-GKI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GKI Kernel
        run: |
          git clone --depth=1 --branch "${{ github.event.inputs.gki_branch }}" "${{ github.event.inputs.gki_repo }}" gki-kernel

      - name: Checkout DTB Source (Kernel 4.9)
        run: |
          git clone --depth=1 --branch "${{ github.event.inputs.dtb_branch }}" "${{ github.event.inputs.dtb_repo }}" dtb-4.9

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential libncurses5-dev bison flex libssl-dev libelf-dev curl git gcc make clang lld dtc

      - name: Inject DTB 4.9 ke GKI Source
        run: |
          mkdir -p gki-kernel/arch/arm64/boot/dts/qcom
          cp -r dtb-4.9/* gki-kernel/arch/arm64/boot/dts/qcom/

      - name: Download Clang Toolchain
        run: |
          mkdir -p toolchains
          curl -L https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/master-kernel/clang-r416183b.tar.gz?format=TEXT | base64 -d | tar -xz -C toolchains

      - name: Build Kernel Image.gz-dtb
        run: |
          cd gki-kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=aarch64-linux-gnu-
          export PATH=$GITHUB_WORKSPACE/toolchains/clang-r416183b/bin:$PATH

          make O=out ${{ github.event.inputs.device_defconfig }} CC=clang
          make O=out -j$(nproc) CC=clang Image.gz-dtb

      - name: Upload Image.gz-dtb
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image-gz-dtb
          path: gki-kernel/out/arch/arm64/boot/Image.gz-dtb
