# GitHub Actions Workflow: Port GKI 5.4 to Non-GKI Kernel (DTB & defconfig dari kernel 4.9)
# ==========================================================================================
# Fungsi:
# - Clone kernel GKI 5.4 dari repositori GitHub
# - Clone DTB dan device_defconfig dari kernel 4.9 source tree lain
# - Build kernel non-GKI dengan DTB dan defconfig dari kernel 4.9
# - Upload hasil: Image.gz-dtb

name: Port-GKI-5.4-to-Non-GKI

on:
  workflow_dispatch:
    inputs:
      gki_repo:
        description: 'URL repositori GKI Kernel 5.4'
        required: true
        default: 'https://github.com/pundiramit/linux'
      gki_branch:
        description: 'beryllium-mainline'
        required: false
        default: 'main'
      non_gki_repo:
        description: 'URL repositori kernel 4.9 (sumber DTB dan defconfig)'
        required: true
        default: 'https://github.com/RONNIE158/android_kernel_xiaomi_sdm845'
      non_gki_branch:
        description: 'lineage-21'
        required: false
        default: 'main'
      defconfig_path:
        description: 'Path relatif ke file defconfig di repo kernel 4.9 (contoh: arch/arm64/configs/beryllium_defconfig)'
        required: true

jobs:
  build:
    name: Port & Build Non-GKI Kernel
    runs-on: ubuntu-latest

    steps:
      - name: Clone GKI Kernel Source
        run: |
          git clone --depth=1 --branch "${{ github.event.inputs.gki_branch }}" "${{ github.event.inputs.gki_repo }}" gki-kernel

      - name: Clone Kernel 4.9 Source (defconfig & DTB)
        run: |
          git clone --depth=1 --branch "${{ github.event.inputs.non_gki_branch }}" "${{ github.event.inputs.non_gki_repo }}" kernel-4.9

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential libncurses5-dev bison flex libssl-dev libelf-dev curl git gcc make clang lld dtc

      - name: Copy DTB & defconfig dari kernel 4.9 ke GKI
        run: |
          mkdir -p gki-kernel/arch/arm64/boot/dts/qcom
          cp -r kernel-4.9/arch/arm64/boot/dts/qcom/* gki-kernel/arch/arm64/boot/dts/qcom/
          cp kernel-4.9/${{ github.event.inputs.defconfig_path }} gki-kernel/arch/arm64/configs/

      - name: Download Clang Toolchain
        run: |
          mkdir -p toolchains
          curl -L https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/master-kernel/clang-r416183b.tar.gz?format=TEXT | base64 -d | tar -xz -C toolchains

      - name: Build Kernel Image.gz-dtb
        run: |
          cd gki-kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=aarch64-linux-gnu-
          export PATH=$GITHUB_WORKSPACE/toolchains/clang-r416183b/bin:$PATH

          defconfig_file=$(basename "${{ github.event.inputs.defconfig_path }}")
          make O=out $defconfig_file CC=clang
          make O=out -j$(nproc) CC=clang Image.gz-dtb

      - name: Upload Image.gz-dtb
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image-gz-dtb
          path: gki-kernel/out/arch/arm64/boot/Image.gz-dtb
